#!/bin/bash

source ./function

CONTAINER_NAME="postgre_server"

IMAGE_NAME=$CONTAINER_NAME
VERSION=1.0

ROOT_PATH="/home/test/postgreSQL"
VOLUME_DATA_PATH="/home/test/postgreSQL/data"
DEFAULT_DATA_PATH="/var/lib/postgresql/data"


# Check Image
IMAGE_STATUS=$(docker images -q $IMAGE_NAME:$VERSION)

if [ -n "$IMAGE_STATUS" ]; then
	EchoY "$IMAGE_NAME:$VERSION is exist" && echo ""

else 
	EchoY "Building $IMAGE_NAME:$VERSION" && echo ""

	docker build -t $IMAGE_NAME:$VERSION . 
	
	CopyConfig
fi


# Check Container
CONTAINER_STATUS=$(docker inspect --format="{{.State.Running}}" $CONTAINER_NAME 2>/dev/null)

if [ "$CONTAINER_STATUS" == "true" ]; then
	EchoY "$CONTAINER_NAME is running"
	docker exec -it $CONTAINER_NAME bash
else
	EchoY "Running $CONTAINER_NAME now"
	
	docker run \
	--name $CONTAINER_NAME \
	-v $VOLUME_DATA_PATH:$DEFAULT_DATA_PATH \
	-e POSTGRES_USER=mike \
	-e POSTGRES_PASSWORD=password2222 \
	-p 5432:5432 \
	-d \
	$IMAGE_NAME:$VERSION
	
	/usr/pgadmin4/bin/pgadmin4 &
	
	docker exec -it $CONTAINER_NAME bash
fi
	


